# Generated by Django 5.0.6 on 2026-04-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Участник игры',
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.CharField(blank=True, max_length=100)),
                ('stats', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Результат игры',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('sport_id', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=1, default=1.5, max_digits=3)),
                ('players_needed', models.PositiveSmallIntegerField(default=10)),
                ('players_total', models.PositiveSmallIntegerField(default=10)),
                ('level', models.CharField(choices=[('ANY', 'Любой'), ('BEGINNER', 'Новичок'), ('INTERMEDIATE', 'Любитель'), ('ADVANCED', 'Продвинутый')], default='ANY', max_length=20)),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('confirmed', 'Подтверждён'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='waiting', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='chats.chatroom')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['date_time'],
            },
        ),
    ]
