# Generated by Django 5.0.6 on 2026-04-15 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='venues.venue'),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='games.game'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='mvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['sport_id', 'status'], name='games_game_sport_i_6ea0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['date_time'], name='games_game_date_ti_7b28cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameparticipant',
            unique_together={('game', 'user')},
        ),
    ]
