# Generated by Django 5.0.6 on 2026-04-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='link_2gis',
            field=models.URLField(blank=True, max_length=500, verbose_name='Ссылка на 2ГИС'),
        ),
    ]
