# Generated by Django 5.0.6 on 2026-06-22 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('venues', '0002_venue_link_2gis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('sport_id', models.CharField(blank=True, max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=40)),
                ('players_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('contacted', 'Связались'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='new', max_length=20)),
                ('source', models.CharField(default='mobile', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='venues.venue')),
            ],
            options={
                'verbose_name': 'Заявка на бронь',
                'verbose_name_plural': 'Заявки на бронь',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['venue', 'status'], name='bookings_bo_venue_i_da88dc_idx'), models.Index(fields=['phone', 'created_at'], name='bookings_bo_phone_64a851_idx')],
            },
        ),
    ]
