# Generated by Django 5.0.6 on 2026-04-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
