# Generated by Django 5.0.6 on 2026-04-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('game', 'Игровой чат'), ('direct', 'Личный чат'), ('venue', 'Чат площадки')], default='game', max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='chat_avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Чат-комната',
                'verbose_name_plural': 'Чат-комнаты',
            },
        ),
    ]
